In [ ]:
# Example nested dictionary structure
sliding_windows = {
    "1-3": {
        "elements": [True, False, True, False, True, False, True, False, True, False,
                     True, False, True, False, True, False, True],
        "size": None
    },
    "2-3": {
        "elements": [ False, False, True, False, False, True, False,
                     True, False, True, False, True, False, True, False, True, False],
        "size": None
    },
    "4-5": {
        "elements": [True, False, True, False, True, False, True],
        "size": None
    },
    "5-6": {
        "elements": [True, True, False, True, False],
        "size": None
    },
    "6-7": {
        "elements": [True, False, True, False, True, False, True, False, True, False,
                     True, False, True, False, True, False, True, False, True, False,
                     True, False, True, False, True, False, True, False, True, False,
                     True, False, True, False, True, False, True, False, True, False],
        "size": None
    }
}


In [ ]:
for pair_key, pair_data in sliding_windows.items():
    sliding_windows[pair_key]["size"] = len(sliding_windows[pair_key]["elements"])

# Print the nested dictionary structure
for pair_key, pair_data in sliding_windows.items():
    print(sliding_windows[pair_key]["size"],len(sliding_windows[pair_key]["elements"]))

In [ ]:
sliding_windows["1-3"]["elements"] = [True, False, True, False, True, False, True, False, True, False,
                                        True, False, True, False, True, False, True, False, True, False,
                                        True, False, True, False, True, False, True, False, True, False,
                                        True, False, True, False, True, False, True, False, True, False]

In [ ]:
for pair_key, pair_data in sliding_windows.items():
    print(sliding_windows[pair_key]["size"],len(sliding_windows[pair_key]["elements"]))

In [ ]:

keys_to_delete = []  # Create a list to store keys to delete

for pair_key, pair_data in sliding_windows.items():
    if len(sliding_windows[pair_key]["elements"]) == sliding_windows[pair_key]["size"] :
        print("worked")
        keys_to_delete.append(pair_key)
    else:
        pair_data["size"] = len(pair_data["elements"])

# Delete items outside the loop
for key in keys_to_delete:
    del sliding_windows[key]


In [ ]:
for pair_key, pair_data in sliding_windows.items():
    print(sliding_windows[pair_key]["size"],len(sliding_windows[pair_key]["elements"]))
    print("//////////////////////////////////////////////////")

In [ ]:
for i in sliding_windows.keys():
    print(i)

In [1]:
import cv2
import numpy as np

img = cv2.imread("img.png")


In [2]:

original_pt = np.float32([[97, 1418], [2533, 1429], [1507, 337], [960, 342]])
 
# 4 Points on the new image
new_pt = np.float32([[0,0],[2200,0],[1200,0],[2200,1200]])
M = cv2.getPerspectiveTransform(original_pt,new_pt)
 
# Feed into warpAffrine function to perform our skew
image = cv2.warpPerspective(img,M,(2000,1000))

In [3]:
print(M)

[[-1.36306379e+00 -1.09323797e+00  1.68242863e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.12541025e-03  2.35069703e-04  1.00000000e+00]]


In [ ]:
cv2.imshow("asdas",image)
cv2.waitKey(0)